### PR TITLE
AST-5007 feat(select): add autocomplete functionality

### PR DESCRIPTION
**Pull request by rahulkeerthi**
Changes:
- add autocomplete logic and UX changes to Select component (single and multiple types)
- remove `label` prop and replace with `labels` prop to extend support for more custom labels (placeholder, no options, error)

Other
- add StorySource add-on to Storybook to see story code in Storybook itself

### CODE REVIEW

**Comment by nckhell** [comment]
[C] Nitpick, but add an extra top offset of 1px to the dropdown menu so the full border of the input box is visible. Now the dropdown menu overlaps the border by 1px and looks a bit off.

Screenshot 2023-03-28 at 15 50 07

**Comment by nckhell** [comment]
[S] https://www.loom.com/share/602d72dd7e1641c68b5f3ddab3bb41c7

**Review by nckhell — CHANGES_REQUESTED** [review]

**Comment by nckhell** [comment]
[Q] I am curious to see a story where the answer options are actual sentences instead of a simple word like "First option". Probably still needs a bit of tweaking to render that in an okay-ish way?

**Comment by rahulkeerthi** [comment]
> [Q] I am curious to see a story where the answer options are actual sentences instead of a simple word like "First option". Probably still needs a bit of tweaking to render that in an okay-ish way?

Added props for filtering, showCount and displayMaxLength
- filtering prop addresses the requirement for a basic select component config
- showCount and displayMaxLength offer devs options for display UX when options labels are long

Added stories to show behaviour without filtering 

NB: used filtering instead of autocomplete because autoComplete is a reserved input prop that means something else (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)

**Comment by nckhell** [comment]
@rahulkeerthi Last comment: from a UX perspective there should be a clear difference between a regular input component and a select component.

Currently, the select component looks like a regular input field and nothing tells me I can actually select something
Screenshot 2023-03-29 at 13 41 05

Regular practice is to use a trailing chevron icon to show users it's a select:
Screenshot 2023-03-29 at 13 42 11

Add that, and we are good to go.

**Pull request merged**
